### ISSUE TITLE
Titlebar CSS broken

### ISSUE THREAD

**Issue by tuck3r** [cold12/Stylish-Dark-Slack#3]
The CSS in the titlebar is broken in both channels and in conversations.

Browser: Chrome -- Version 49.0.2623.75 (64-bit)
OS: Arch Linux

![image](https://cloud.githubusercontent.com/assets/10316811/13671855/56d7a78e-e6a0-11e5-8277-43b80e673672.png)

**Comment by m-renaud** [comment]
Not a proper solution but I've made the following changes locally to fix the style:

```css
#channel_title { color: #cccccc }
#client_body:not(.onboarding):before { background: #2A2E39; }
.message:hover { background: #4d394b !important }
#footer { background: #2A2E39 !important }
```
